services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: always
    volumes:
      - ./django_transaction_app:/app/django_transaction_app
      - static_volume:/app/django_transaction_app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    env_file: .env
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: "no"
    ports:
      - "3306:3306"
    expose:
      - 3306
    env_file: .env
    volumes:
      - ./dbdata:/var/lib/mysql/
  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - static_volume:/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  static_volume: