# Generated by Django 5.0.4 on 2024-05-01 08:52

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("transaction", "0001_initial"),
        ("transaction", "0002_alter_wallet_balance"),
        ("transaction", "0003_alter_transaction_wallet_id"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Balance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=18, verbose_name="Amount"
                    ),
                ),
                (
                    "txid",
                    models.CharField(max_length=255, unique=True, verbose_name="txid"),
                ),
                (
                    "wallet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
        ),
    ]
