# Generated by Django 5.0.4 on 2024-04-29 05:37

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=20,
                verbose_name="Balance",
            ),
        ),
    ]
